### ISSUE TITLE
Google Drive link 

### ISSUE THREAD

**Issue by ogencoglu** [hlz0606/SSPCM#1]
Hi,

Thanks for the dataset. Do you have a Google Drive or Dropbox link for the ones who does not have Baidu cloud access or account?

**Comment by MiraPurkrabek** [comment]
I second this. Any chance to upload somewhere where the download would be available, @hlz0606 ?

**Comment by lcc815** [comment]
I updated the data here:
https://drive.google.com/drive/folders/1YozM5PSXKfyGbMwaxYPiz-8vbMBo7xoB?usp=drive_link
